SWP391_ShoppingOnline/src/java/model/Order.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Date;
import java.text.DecimalFormat;

/**
 *
 * @author Dell
 */
public class Order {

    private int orderID;
    private int orderCusID;
    private Date orderDate;
    private double orderTotalPrice;
    private String orderContactName;
    private String orderPhone;
    private String orderAddress;
    private int orderSoID;
    private int orderAdID;
    private String orderNote;

    public Order() {
    }

    public Order(int orderID, int orderCusID, Date orderDate, double orderTotalPrice, String orderContactName, String orderPhone, String orderAddress, int orderSoID, int orderAdID, String orderNote) {
        this.orderID = orderID;
        this.orderCusID = orderCusID;
        this.orderDate = orderDate;
        this.orderTotalPrice = orderTotalPrice;
        this.orderContactName = orderContactName;
        this.orderPhone = orderPhone;
        this.orderAddress = orderAddress;
        this.orderSoID = orderSoID;
        this.orderAdID = orderAdID;
        this.orderNote = orderNote;
    }
    
    
    public String getOrderStatus(){
        if(orderSoID == 1) return "Pending";
        if(orderSoID == 2) return "Processing";
        if(orderSoID == 3) return "Shipping";
        if(orderSoID == 4) return "Delivered";
        if(orderSoID == 5) return "Rejected";
        return "Canceled";
    }

    public int getOrderID() {
        return orderID;
    }

    public void setOrderID(int orderID) {
        this.orderID = orderID;
    }

    public int getOrderCusID() {
        return orderCusID;
    }

    public void setOrderCusID(int orderCusID) {
        this.orderCusID = orderCusID;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public double getOrderTotalPrice() {
        return orderTotalPrice;
    }

    public void setOrderTotalPrice(double orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }

    public String getOrderContactName() {
        return orderContactName;
    }

    public void setOrderContactName(String orderContactName) {
        this.orderContactName = orderContactName;
    }

    public String getOrderPhone() {
        return orderPhone;
    }

    public void setOrderPhone(String orderPhone) {
        this.orderPhone = orderPhone;
    }

    public String getOrderAddress() {
        return orderAddress;
    }

    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }

    public int getOrderSoID() {
        return orderSoID;
    }

    public void setOrderSoID(int orderSoID) {
        this.orderSoID = orderSoID;
    }

    public int getOrderAdID() {
        return orderAdID;
    }

    public void setOrderAdID(int orderAdID) {
        this.orderAdID = orderAdID;
    }

    public String getOrderNote() {
        if(orderNote.length()>0 && orderNote.charAt(0) == '💵')
            return orderNote.substring(2);
        
        return orderNote;
    }

    public void setOrderNote(String orderNote) {
        this.orderNote = orderNote;
    }
    
    public String getRawNote(){
        return this.orderNote;
    }
    
    public String getPrice(){
        DecimalFormat decimalFormat = new DecimalFormat("###,###.###");
        String formattedNumber = decimalFormat.format(orderTotalPrice);
        return formattedNumber;
    }
    
    public String getPaymentMethod(){
        if(orderNote.length()>0 && orderNote.charAt(0) == '💵')
            return "Full payment";
        
        return "Deposit 500.000";
    }

    @Override
    public String toString() {
        return "Order{" + "orderID=" + orderID + ", orderCusID=" + orderCusID + ", orderDate=" + orderDate + ", orderTotalPrice=" + orderTotalPrice + ", orderContactName=" + orderContactName + ", orderPhone=" + orderPhone + ", orderAddress=" + orderAddress + ", orderSoID=" + orderSoID + ", orderAdID=" + orderAdID + ", orderNote=" + orderNote + '}';
    }
    
}

SWP391_ShoppingOnline/src/java/model/ProductDetail.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.ProductDetailDAO;

/**
 *
 * @author huytu
 */
public class ProductDetail {
    private int pdID;
    private int	pdProID;
    private String pdColor;
    private int	pdSold;
    private int	pdStatus;

    public ProductDetail() {
    }

    public ProductDetail(int pdID, int pdProID, String pdColor, int pdSold, int pdStatus) {
        this.pdID = pdID;
        this.pdProID = pdProID;
        this.pdColor = pdColor;
        this.pdSold = pdSold;
        this.pdStatus = pdStatus;
    }

    public int getPdID() {
        return pdID;
    }

    public void setPdID(int pdID) {
        this.pdID = pdID;
    }

    public int getPdProID() {
        return pdProID;
    }

    public void setPdProID(int pdProID) {
        this.pdProID = pdProID;
    }

    public String getPdColor() {
        return pdColor;
    }

    public void setPdColor(String pdColor) {
        this.pdColor = pdColor;
    }

    public int getPdSold() {
        return pdSold;
    }

    public void setPdSold(int pdSold) {
        this.pdSold = pdSold;
    }

    public int getPdStatus() {
        return pdStatus;
    }

    public void setPdStatus(int pdStatus) {
        this.pdStatus = pdStatus;
    }

    public String getPdImage() {
        return new ProductDetailDAO().getProductDetailImage(pdID+"");
    }
    
    @Override
    public String toString() {
        return "ProductDetail{" + "pdID=" + pdID + ", pdProID=" + pdProID + ", pdColor=" + pdColor + ", pdSold=" + pdSold + ", pdStatus=" + pdStatus + '}';
    }
    
    
}

SWP391_ShoppingOnline/src/java/controller/admin/LoginAdminController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.admin;

import dal.AdminDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import model.Admin;
import util.Encode;

/**
 *
 * @author BEAN
 */
public class LoginAdminController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet LoginAdminController</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet LoginAdminController at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("/jsp/login-admin.jsp").forward(request, response);
        HttpSession session = request.getSession();
        session.removeAttribute("alert");
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String username = request.getParameter("username");
        String password = request.getParameter("password");
        System.out.println(username);
        AdminDAO adminDAO = new AdminDAO();

        Admin admin = adminDAO.login(username, Encode.hashPassword(password));

        //   Admin admin = adminDAO.login(username, password);
        if (admin != null) {
            if (admin.getAdStatus() == 0) {
                request.setAttribute("message", "Your account has blocked !");
                request.getRequestDispatcher("/jsp/login-admin.jsp").forward(request, response);
            } else {
                int role = adminDAO.getRole(username);
                //save infor to session
                HttpSession session = request.getSession();
                session.setAttribute("username", username);
                session.setAttribute("role", role);
                session.setAttribute("admin", admin);
                if (role == 3) {
                    //response.sendRedirect("../sale/manageOrder");
                    response.sendRedirect("./home");
                } else if (role == 1) {
                    response.sendRedirect("./manage");
                } else  {
                    response.sendRedirect("../marketing/manage-product");
                }
            }
        } else {
            request.setAttribute("message", "Wrong username or password");
            request.getRequestDispatcher("/jsp/login-admin.jsp").forward(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

SWP391_ShoppingOnline/src/java/controller/common/ForgotPasswordController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.common;

import dal.CustomerDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.Random;
import model.Customer;
import util.Encode;
import util.SendMail;
/////////
/**
 *
 * @author BEAN
 */
public class ForgotPasswordController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>PO
     *
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {

        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String service = request.getParameter("service");
        if (service == null) {
            service = "forgotPassword";
            request.getRequestDispatcher("jsp/forgotPassword.jsp").forward(request, response);
        }
        if (service.equals("validateOtp")) {
            request.getRequestDispatcher("jsp/enterOtp.jsp").forward(request, response);
        }
        if (service.equals("resetPassword")) {
            request.getRequestDispatcher("jsp/newPassword.jsp").forward(request, response);
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String service = request.getParameter("service");
        if (service == null) {
            service = "forgotPassword";
        }
        if (service.equals("forgotPassword")) {
            String email = request.getParameter("email");
            CustomerDAO daoCustomer = new CustomerDAO();
            Customer customer = daoCustomer.checkCustomerExistByEmail(email);
            if (customer == null) {
                request.setAttribute("message", "Email is not Exist");
                request.getRequestDispatcher("jsp/forgotPassword.jsp").forward(request, response);
            } else {
                String sendTo = customer.getCusEmail();

                HttpSession session = request.getSession();
                session.setAttribute("emailResetPassword", sendTo);
                String subject = "Reset Password";
                String otp = SendMail.generateOTP(6);
                session.setAttribute("generatedOTP", otp);
                String content = "<h1>iLocalShop Reset Password</h1>"
                        + "<p>Your OTP (One Time Password) is: <strong>" + otp + "</strong></p>"
                        + "<p>Please use this OTP to reset your password.</p>";
                String user = "vitaminshare2022@gmail.com";
                String password = "odhv cisw gmgk bbjl";
                SendMail.send(sendTo, subject, content, user, password);
                request.getRequestDispatcher("jsp/enterOtp.jsp").forward(request, response);
            }
        }
        if (service.equals("validateOtp")) {
            String userEnteredOTP = request.getParameter("otp");
            HttpSession session = request.getSession();
            String generatedOTP = (String) session.getAttribute("generatedOTP");
            if (userEnteredOTP.equals(generatedOTP)) {
                response.sendRedirect("forgotPassword?service=resetPassword");
                session.removeAttribute("generatedOTP");
            } else {
                request.setAttribute("message", "Invalid OTP. Please try again.");
                request.getRequestDispatcher("jsp/enterOtp.jsp").forward(request, response);                                                                                                        
            }
        }
        if (service.equals("resetPassword")) {
            String newPassword = request.getParameter("newPassword");
            String confirmPassword = request.getParameter("confirmPassword");
            HttpSession session = request.getSession();
            String emailResetPassword = (String) session.getAttribute("emailResetPassword");
            
            if (!newPassword.equals(confirmPassword)) {
                request.setAttribute("message", "Passwords do not match. Please try again!");
                request.getRequestDispatcher("jsp/newPassword.jsp").forward(request, response);
            } else if (newPassword.length() < 8 || newPassword.length() > 20) {
                request.setAttribute("message", "Password must be between 8 and 20 characters.");
                request.getRequestDispatcher("jsp/newPassword.jsp").forward(request, response);
            } else {
                CustomerDAO daoCustomer = new CustomerDAO();
                //hashing 
                daoCustomer.changePassword(emailResetPassword,Encode.hashPassword(newPassword));
                response.sendRedirect("home");
            }
        }
    }
}

SWP391_ShoppingOnline/web/jsp/address.jsp
<%-- 
    Document   : address
    Created on : Oct 11, 2023, 12:55:32 AM
    Author     : Dell
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Address | iLocal Shop</title>
        <link rel="icon" type="image/x-icon" href="img/logo.png">
        <!-- Link Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

        <!-- Link File CSS -->
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <jsp:include page="../header.jsp"></jsp:include>

            <a href="profile" type="button"style="font-size: 17px; margin-left: 55px; ">
                <svg width="10px" height="10px" viewBox="159.94277954101562 191.94850158691406 736.0572204589844 640.074462890625" class="icon" xmlns="http://www.w3.org/2000/svg"><path fill="#000000" d="M224 480h640a32 32 0 110 64H224a32 32 0 010-64z"/><path fill="#000000" d="M237.248 512l265.408 265.344a32 32 0 01-45.312 45.312l-288-288a32 32 0 010-45.312l288-288a32 32 0 1145.312 45.312L237.248 512z"/></svg>
                 Your profile</a>
            <div class="row" style="margin-left: 110px; margin-right: 100px; margin-bottom: 50px; margin-top: 20px">
                <div class="info">
                    <h2>Address information</h2>
                    <h4 style="font-weight: bolder; margin: 5px">Hello, ${customer.cusContactName}!</h4>
                <h4 style="margin: 5px">Update your account information to have the best store policies and security</h4>
                <div style="margin-left: 980px; font-size: 12px;">
                </div>
                <div style="border:solid 1px #dedede; padding:30px; padding-bottom: 80px;width: 40%;">
                    <h3 style="margin: 0;padding: 5px;border-bottom: 1px solid #ccc;margin-bottom: 10px;">${customer.cusContactName}</h3>
                    <p>
                        <strong style="display:inline-block;width:80px">Address:</strong>${addressDetail}<br/>
                        <strong style="display:inline-block;width:80px">City:</strong>${city}<br/>
                        <strong style="display:inline-block;width:80px">District:</strong>${district}<br/>
                        <strong style="display:inline-block;width:80px">Ward:</strong>${ward}<br/>
                        <strong style="display:inline-block;width:80px">Phone:</strong>${customer.cusPhone}<br/>
                    </p>
                    <a class="btn" style="float: left; font-size: 15px; padding: 10px; margin-top: 15px; margin-left: 180px" href="${pageContext.request.contextPath}/updateAddress">Update</a>
                </div>
            </div>
        </div>        
        <jsp:include page="../footer.jsp"></jsp:include>
    </body>
</html>

SWP391_ShoppingOnline/web/jsp/order-detail.jsp
<%-- 
    Document   : order-detail
    Created on : Oct 24, 2023, 3:53:51 PM
    Author     : Dell
--%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${product.proName} | iLocal Shop</title>
        <link rel="icon" type="image/x-icon" href="img/logo.png">
        <!-- Link Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <!-- Link File CSS -->
        <link rel="stylesheet" href="css/styles.css">
        <!-- Add your custom CSS styles here -->
        <link rel="stylesheet" href="css/product-detail.css">
    </head>
    <body>
        <style>
            h2{
                font-family: 'Roboto',sans-serif;
                font-size: 26px;
                margin-top: 20px;
                margin-bottom: 10px;
                font-weight: 500;
                line-height: 1.1;
                color: inherit;
            }
            h4{
                font-family: 'Roboto',sans-serif;
                margin-top: 20px;
                margin-bottom: 10px;
                line-height: 1.1;
                color: #333;
                font-weight: lighter;
            }
            table{
                width: 100%;
                background-color: transparent;
                border-spacing: 0;
                border-collapse: collapse;
                /*border-color: gray;*/
                text-indent: initial;
                display: table;
                border: 2px gray solid;
            }
            *{
                /*                margin: 10px;
                                padding: 110px;*/
            }
            th, td{
                border: 2px gray solid;
            }
            .btn{
                /*float: right;*/

                margin: 10px 0px;
                background: #e24d85;
                color: #fff;
                padding: 10px 15px;
                font-weight: bold;
                display: inline-block;
                font-size: 14px;
                line-height: 1.42857143;
                text-align: center;
                white-space: nowrap;
                vertical-align: middle;
                -ms-touch-action: manipulation;
                touch-action: manipulation;
                cursor: pointer;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
                border: 1px solid transparent;
                border-radius: 4px;
            }
            .info{
                /*width: 80%;*/
            }
            td{
                padding-left: 10px;
                padding-right: 10px;
                text-align: center;
            }
        </style>

        <jsp:include page="../header.jsp"></jsp:include>

            <div class="row" style="margin-left: 110px; margin-right: 100px; margin-bottom: 50px">
                <div class="info">
                    <h2>Order detail</h2>
                    <h4 style="font-weight: bolder; margin: 5px">Hello, ${customer.cusContactName}!</h4>
                    <h4 style="font-weight: bolder; margin: 5px">Total price: ${order.price}</h4>
                    <h4 style="font-weight: bolder; margin: 5px">Note: ${order.orderNote}</h4>
                <!--<h4 style="margin: 5px">Update your account information to have the best store policies and security</h4>-->
                <div style="margin-left: 80%; font-size: 12px;">
                    <a href="profile" type="button" class="btn" style="margin-top: 0">Return to your profile</a>
                </div>
                <table>
                    <thead>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Color</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    </thead>
                    <tbody><tr>
                        <c:forEach items="${productOfOrderList}" var="o">
                            <%--<c:forEach items="${orderDetailList}" var="od">--%>
                            <tr>
                                <td class="product-image" style="text-align: center; width: 10%; padding: 5px"><img src="pdimg/${o.pdImage}" alt="alt"/></td>
                                <td style="text-align: center">${o.proName}</td>
                                <td style="">${o.pdColor}</td>
                                <td><span><fmt:formatNumber value="${o.proPrice}" type="number" pattern="#,##0" /> VND</span></td>
                                <td style="text-align: center">${o.odQuantity}</td>
                            </tr>
                            <%--</c:forEach>--%>
                        </c:forEach>
                    </tbody>
                </table>
                
                
            </div>
        </div>
    </div>
    <jsp:include page="../footer.jsp"></jsp:include>

</body>
</html>

SWP391_ShoppingOnline/web/jsp/userProfile.jsp
<%-- 
    Document   : userProfile
    Created on : Oct 2, 2023, 10:34:35 AM
    Author     : Dell
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Profile | iLocal Shop</title>
        <link rel="icon" type="image/x-icon" href="img/logo.png">
        <!-- Link Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

        <!-- Link File CSS -->
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <style>
            h2{
                font-family: 'Roboto',sans-serif;
                font-size: 26px;
                margin-top: 20px;
                margin-bottom: 10px;
                font-weight: 500;
                line-height: 1.1;
                color: inherit;
            }
            h4{
                font-family: 'Roboto',sans-serif;
                margin-top: 20px;
                margin-bottom: 10px;
                line-height: 1.1;
                color: #333;
                font-weight: lighter;
            }
            table{
                width: 100%;
                background-color: transparent;
                border-spacing: 0;
                border-collapse: collapse;
                /*border-color: gray;*/
                text-indent: initial;
                display: table;
                border: 2px gray solid;
            }
            *{
                /*                margin: 10px;
                                padding: 110px;*/
            }
            th, td{
                border: 2px gray solid;
                text-align: center;
            }
            .btn{
                /*float: right;*/

                margin: 10px 0px;
                background: #e24d85;
                color: #fff;
                padding: 10px 15px;
                font-weight: bold;
                display: inline-block;
                font-size: 14px;
                line-height: 1.42857143;
                text-align: center;
                white-space: nowrap;
                vertical-align: middle;
                -ms-touch-action: manipulation;
                touch-action: manipulation;
                cursor: pointer;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
                border: 1px solid transparent;
                border-radius: 4px;
            }
            .info{
                /*width: 80%;*/
            }
            a:link {
                text-decoration: none;
            }

            a:visited {
                text-decoration: none;
            }

            a:hover {
                text-decoration: underline;
            }

            a:active {
                text-decoration: underline;
            }
        </style>
        <jsp:include page="../header.jsp"></jsp:include>

            <div class="row" style="margin-left: 110px; margin-right: 100px; margin-bottom: 50px">
                <div class="info">
                    <h2>Address information</h2>
                    <h4 style="font-weight: bolder; margin: 5px">Hello, ${customer.cusContactName}!</h4>
                <h4 style="margin: 5px">Update your account information to have the best store policies and security</h4>
                <h4 style="font-weight: bolder">Order information</h4>
                <table>
                    <thead>
                    <th>Order ID</th>
                    <th>Order time</th>
                    <th>Total</th>
                    <th>Payment Method</th>
                    <th>Status</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                        <c:forEach items="${listCusOrder}" var="o">
                            <tr>
                                <td style="text-align: center"><a href="${pageContext.request.contextPath}/order-detail?orderID=${o.orderID}">${o.orderID}</a></td>
                                <td>${o.orderDate}</td>
                                <td><span><fmt:formatNumber value="${o.orderTotalPrice}" type="number" pattern="#,##0" /> VND</span></td>
                                <td>${o.paymentMethod}</td>
                                <td style="text-align:center;">
                                    ${o.getOrderStatus()}
                                </td>
                                <td>
                                    <c:if test="${o.orderSoID == 1}">
                                        <a style="margin-left:20px" href="purchase?ordId=${o.orderID}">Purchase</a>
                                    </c:if>
                                    <c:if test="${o.orderSoID == 4}">
                                        <a style="margin-left:20px" href="SendFeedback?ordId=${o.orderID}">Feedback</a>
                                    </c:if>
                                </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>

                <div class="row">
                    <div style="display: inline-block;">
                        <a href="${pageContext.request.contextPath}/changePassword" type="button" class="btn">Change password</a>
                    </div>
                    <div style="display: inline-block; margin-left: 30px;">
                        <a href="${pageContext.request.contextPath}/address" type="button" class="btn">Address information</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <jsp:include page="../footer.jsp"></jsp:include>    
</body>
</html>