SWP391_ShoppingOnline/src/java/model/Admin.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.AdminDAO;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author BEAN
 */
public class Admin{
    private int adId;
    private String adLastName;
    private String adFirstName;
    private String adUsername;
    private String adPassword;
    private String adImage;
    private Boolean adGender;
    private Date adDob;
    private String adPhone;
    private String adEmail;
    private String adAddress;
    private int adStatus;
    private int adRoleId;

    public Admin() {
    }

    public Admin(int adId, String adLastName, String adFirstName, String adUsername, String adPassword, String adImage, Boolean adGender, Date adDob, String adPhone, String adEmail, String adAddress, int adStatus, int adRoleId) {
        this.adId = adId;
        this.adLastName = adLastName;
        this.adFirstName = adFirstName;
        this.adUsername = adUsername;
        this.adPassword = adPassword;
        this.adImage = adImage;
        this.adGender = adGender;
        this.adDob = adDob;
        this.adPhone = adPhone;
        this.adEmail = adEmail;
        this.adAddress = adAddress;
        this.adStatus = adStatus;
        this.adRoleId = adRoleId;
    }

    public int getAdId() {
        return adId;
    }

    public void setAdId(int adId) {
        this.adId = adId;
    }

    public String getAdLastName() {
        return adLastName;
    }

    public void setAdLastName(String adLastName) {
        this.adLastName = adLastName;
    }

    public String getAdFirstName() {
        return adFirstName;
    }

    public void setAdFirstName(String adFirstName) {
        this.adFirstName = adFirstName;
    }

    public String getAdUsername() {
        return adUsername;
    }

    public void setAdUsername(String adUsername) {
        this.adUsername = adUsername;
    }

    public String getAdPassword() {
        return adPassword;
    }

    public void setAdPassword(String adPassword) {
        this.adPassword = adPassword;
    }

    public String getAdImage() {
        return adImage;
    }

    public void setAdImage(String adImage) {
        this.adImage = adImage;
    }

    public Boolean getAdGender() {
        return adGender;
    }

    public void setAdGender(Boolean adGender) {
        this.adGender = adGender;
    }

    public Date getAdDob() {
        return adDob;
    }

    public void setAdDob(Date adDob) {
        this.adDob = adDob;
    }

    public String getAdPhone() {
        return adPhone;
    }

    public void setAdPhone(String adPhone) {
        this.adPhone = adPhone;
    }

    public String getAdEmail() {
        return adEmail;
    }

    public void setAdEmail(String adEmail) {
        this.adEmail = adEmail;
    }

    public String getAdAddress() {
        return adAddress;
    }

    public void setAdAddress(String adAddress) {
        this.adAddress = adAddress;
    }

    public int getAdStatus() {
        return adStatus;
    }

    public void setAdStatus(int adStatus) {
        this.adStatus = adStatus;
    }

    public int getAdRoleId() {
        return adRoleId;
    }

    public void setAdRoleId(int adRoleId) {
        this.adRoleId = adRoleId;
    }
    
    
    public String getFullName() {
        return adFirstName + " " + adLastName;
    }
    
    public String getRoleName() {
        AdminDAO adminDAO = new AdminDAO();
        String name = adminDAO.getRoleName(adRoleId);
        return name;
    }

    @Override
    public String toString() {
        return "Customer{" + "adId=" + adId + ", adLastName=" + adLastName + ", adFirstName=" + adFirstName + ", adUsername=" + adUsername + ", adPassword=" + adPassword + ", adImage=" + adImage + ", adGender=" + adGender + ", Dob=" + adDob + ", adPhone=" + adPhone + ", adEmail=" + adEmail + ", adAddress=" + adAddress + ", adStatus=" + adStatus + ", adRoleId=" + adRoleId + '}';
    }
    
    
     
    
}

SWP391_ShoppingOnline/src/java/model/ProductDetail.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.ProductDetailDAO;

/**
 *
 * @author huytu
 */
public class ProductDetail {
    private int pdID;
    private int	pdProID;
    private String pdColor;
    private int	pdSold;
    private int	pdStatus;

    public ProductDetail() {
    }

    public ProductDetail(int pdID, int pdProID, String pdColor, int pdSold, int pdStatus) {
        this.pdID = pdID;
        this.pdProID = pdProID;
        this.pdColor = pdColor;
        this.pdSold = pdSold;
        this.pdStatus = pdStatus;
    }

    public int getPdID() {
        return pdID;
    }

    public void setPdID(int pdID) {
        this.pdID = pdID;
    }

    public int getPdProID() {
        return pdProID;
    }

    public void setPdProID(int pdProID) {
        this.pdProID = pdProID;
    }

    public String getPdColor() {
        return pdColor;
    }

    public void setPdColor(String pdColor) {
        this.pdColor = pdColor;
    }

    public int getPdSold() {
        return pdSold;
    }

    public void setPdSold(int pdSold) {
        this.pdSold = pdSold;
    }

    public int getPdStatus() {
        return pdStatus;
    }

    public void setPdStatus(int pdStatus) {
        this.pdStatus = pdStatus;
    }

    public String getPdImage() {
        return new ProductDetailDAO().getProductDetailImage(pdID+"");
    }
    
    @Override
    public String toString() {
        return "ProductDetail{" + "pdID=" + pdID + ", pdProID=" + pdProID + ", pdColor=" + pdColor + ", pdSold=" + pdSold + ", pdStatus=" + pdStatus + '}';
    }
    
    
}

SWP391_ShoppingOnline/src/java/controller/admin/AdminProfileController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.admin;

import dal.AdminDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.MultipartConfig;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.Part;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import model.Admin;
import util.InputValidator;

/**
 *
 * @author BEAN
 */
@MultipartConfig
public class AdminProfileController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet AdminProfileController</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet AdminProfileController at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession();
        Admin ad = (Admin) session.getAttribute("admin");
        AdminDAO daoAdmin = new AdminDAO();
        //check session
        if (ad == null) {
            request.getRequestDispatcher("../admin/login").forward(request, response);
        } else {
            request.setAttribute("ad", daoAdmin.getAdminByAdID(ad.getAdId()));
            request.getRequestDispatcher("/admin-profile.jsp").forward(request, response);
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        String fileName = "";
//        
//        Part filePart = request.getPart("adminImage");
//
//        // Get the filename
//         fileName = getSubmittedFileName(filePart);
//
//        // Define the directory where the file will be saved
//        String uploadPath = getServletContext().getRealPath("") + File.separator + "img";
//        File uploadDir = new File(uploadPath);
//
//        if (!uploadDir.exists()) {
//            uploadDir.mkdir();
//        }
//
//        // Save the file to the server
//        try (InputStream input = filePart.getInputStream();
//             OutputStream output = new FileOutputStream(uploadPath + File.separator + fileName)) {
//            int read;
//            byte[] buffer = new byte[1024];
//            while ((read = input.read(buffer)) != -1) {
//                output.write(buffer, 0, read);
//            }
//        }
        
        HttpSession session = request.getSession();
        Admin ad = (Admin) session.getAttribute("admin");
        String adminFirstName = request.getParameter("adminFirstName");
        String adminLastName = request.getParameter("adminLastName");
        String adminAddress = request.getParameter("adminAddress");
        String adminUsername = request.getParameter("adminUsername");
        ad.setAdFirstName(adminFirstName);
        ad.setAdLastName(adminLastName);
        ad.setAdAddress(adminAddress);
        ad.setAdUsername(adminUsername);
        ad.setAdImage("");
        AdminDAO daoAdmin = new AdminDAO();
        if (InputValidator.isValidName(adminFirstName) && InputValidator.isValidName(adminLastName)) {
            daoAdmin.updateProfileAdmin("", adminFirstName, adminLastName, adminAddress, adminUsername);
            session.removeAttribute("admin");
            session.setAttribute("admin", ad);
            session.setAttribute("alertMessage", true);
            response.sendRedirect("profile");
        } else {
            request.setAttribute("message", "First Name and Last Name can't contain special character!");
            request.getRequestDispatcher("/admin-profile.jsp").forward(request, response);
        }
    }
    
      private String getSubmittedFileName(Part part) {
        String header = part.getHeader("content-disposition");
        String[] elements = header.split(";");
        for (String element : elements) {
            if (element.trim().startsWith("filename")) {
                return element.substring(element.indexOf('=') + 1).trim().replace("\"", "");
            }
        }
        return "";
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
}

SWP391_ShoppingOnline/src/java/controller/admin/ManageOrderDetailController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package controller.admin;

import dal.OrderDAO;
import dal.ProductDAO;
import dal.StatusOrderDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.ArrayList;
import java.util.List;
import model.Item;
import model.Order;
import model.StatusOrder;

/**
 *
 * @author windy
 */
public class ManageOrderDetailController extends HttpServlet {
   
    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ManageOrderDetailController</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ManageOrderDetailController at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
       OrderDAO daoOrder = new OrderDAO();
        ProductDAO daoProduct = new ProductDAO();
        ArrayList<Item> listItem = new ArrayList<Item>();
        StatusOrderDAO daoStatusOrder = new StatusOrderDAO();
        
        String orderID = request.getParameter("orderID");
        Order order = daoOrder.getOrderByOrderID(orderID);
        listItem = daoProduct.getListItemByOrderID(orderID);
        List<StatusOrder> listStatusOrder = daoStatusOrder.getStatusOrderForSale();
        
        request.setAttribute("order", order);
        request.setAttribute("orderID", orderID);
        request.setAttribute("listItem", listItem);
        request.setAttribute("listStatusOrder", listStatusOrder);
        request.getRequestDispatcher("/manageOrderDetail.jsp").forward(request, response);
        
    } 

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        boolean checkUpdate = false;
        int statusOrder = -1;
        OrderDAO daoOrder = new OrderDAO();
        
        String status = request.getParameter("status");
        System.out.println("status can tim ne: " + status);
        String orderID = request.getParameter("orderID");
        
        if(status != null || !status.isEmpty()){
            statusOrder = Integer.parseInt(status);
        }
        
        checkUpdate = daoOrder.updateOrderSoID(orderID, statusOrder);
        
        if(checkUpdate){
            request.setAttribute("orderID", orderID);
            doGet(request, response);
        } 
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

SWP391_ShoppingOnline/web/admin-adminDetails.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Manage Admin | iLocal Shop</title>
        <link rel="icon" type="image/x-icon" href="${pageContext.request.contextPath}/img/logo.png">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <!-- Include Bootstrap CSS via CDN link -->
        <!-- ======= Styles ====== -->
        <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/admin_manager.css">
    </head>

    <body>
        <div class="container-fluid">
            <!-- Navigation -->
            <jsp:include page="admin-navigation.jsp"></jsp:include>

                <!-- Main Content -->
                <div class="main" style="margin-left: 50px; margin-right: 50px;">
                    <div class="topbar">
                        <!-- <div class="toggle">
        <ion-icon name="menu-outline"></ion-icon>
    </div>
    <div class="user">
        <img src="assets/imgs/customer01.jpg" alt="">
    </div> -->
                    </div>

                    <div class="row" style="margin-right: 70px;  padding: 10px; border: 1.5px solid #000;">
                        <input type="hidden" id="pageNo" name="pageNo" value="${currentPage}">
                    <div class="col-12" style="margin-bottom: 40px;">
                        <h1>Account details</h1>
                    </div>
                    <form action="admin-details" method="post">
                        <input type="text" value="${data.adId}" name="id" hidden>
                        <div class="form-group row">
                            <div class="col-4">
                                <label for="firstName">First Name:</label>
                                <input type="text" class="form-control" id="firstName" name="firstName"
                                       value="${data.adFirstName}" required>
                            </div>
                            <div class="col-4">
                                <label for="lastName">Last Name:</label>
                                <input type="text" class="form-control" id="lastName" name="lastName"
                                       value="${data.adLastName}" required>
                            </div>
                            <div class="col-4">
                                <label for="email">Date Of Birth:</label>
                                <input type="date" class="form-control" id="dob" name="dob"
                                       value="${data.adDob}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-4">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" id="email" name="email"
                                       value="${data.adEmail}" required>
                            </div>
                            <div class="col-4">
                                <label for="phone">Phone Number:</label>
                                <input type="text" class="form-control" id="phone" name="phone"
                                       value="${data.adPhone}">
                            </div>
                            <div class="col-4">
                                <label for="phone">Adress:</label>
                                <input type="text" class="form-control" id="address" name="address"
                                       value="${data.adAddress}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-4">
                                <label for="username">Username:</label>
                                <input type="text" class="form-control" id="username" name="username"
                                       value="${data.adUsername}" readonly>
                            </div>

                            <div class="col-2">
                                <label for="roleId">Role:</label>
                                <select class="form-control" id="roleId" name="roleId">
                                    <c:forEach items="${listRole}" var="role">
                                        <option value="${role.roleID}" ${role.roleID==data.adRoleId ? 'selected'
                                                         : '' }>
                                                    ${role.roleName}
                                                </option>
                                        </c:forEach>
                                    </select>
                                </div>
                                <div class="col-2">
                                    <label for="roleId">Status:</label>
                                    <select class="form-control" id="status" name="status">
                                        <option value="1" ${status==1 ? 'selected' : '' }>Active</option>
                                        <option value="0" ${status==0 ? 'selected' : '' }>In-Active</option>
                                    </select>
                                </div>
                            </div>
                          <a class="btn btn-primary" href="./manage">Cancel</a>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>

                </div>
            </div>
        </body>


        <!-- =========== Scripts =========  -->
        <script src="js/admin_manager.js"></script>
        <!-- ====== ionicons ======= -->
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    </html>

SWP391_ShoppingOnline/web/marketing-manage-editProductStock.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Product Manager | iLocal Shop</title>
        <link rel="icon" type="image/x-icon" href="img/logo.png">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <!-- Include Bootstrap CSS via CDN link -->
        <!-- ======= Styles ====== -->
        <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/admin_manager.css">

        <style>
            .image-preview-container {
                display: flex;
                align-items: center;
            }

            .image-preview {
                width: 15%; /* Đặt kích thước hiển thị ảnh */
                height: auto; /* Đảm bảo tỷ lệ khung hình bảo toàn */
                border: 1px solid #ccc; /* Đường viền để phân biệt vùng ảnh */
            }

            .file-input {
                margin-left: 10px; /* Khoảng cách giữa ảnh và nút chọn tệp tin */
            }

            label{
                font-weight: bold;
            }
        </style>

    </head>

    <body>
        <div class="container-fluid">
            <!-- Navigation -->
            <jsp:include page="admin-navigation.jsp"></jsp:include>

                <!-- Main Content -->
                <div class="main" style="margin-left: 50px; margin-right: 50px;">
                    <div class="topbar">
                        <!-- <div class="toggle">
        <ion-icon name="menu-outline"></ion-icon>
    </div>
    <div class="user">
        <img src="assets/imgs/customer01.jpg" alt="">
    </div> -->
                    </div>

                    <div class="row" style="margin-right: 70px;  padding: 10px; border: 1.5px solid #000;">
                        <input type="hidden" id="pageNo" name="pageNo" value="${currentPage}">
                    <div class="col-12" style="margin-bottom: 40px;">
                        <h1>Product details</h1>
                        <c:if test="${param.error != null}">
                            <h6 style="color: red;">In-valid information to add new customer!</h6>
                        </c:if>
                    </div>
                    <form action="edit-productStock" method="post" enctype="multipart/form-data"> 
                        <input type="text" value="${pdStock.proID}" name="proId" hidden>
                        <input type="text" value="${pdStock.pdId}" name="pdID" hidden>
                        <input type="text" value="${pdStock.pdImage}" name="imageOld" hidden>



                        <div class="form-group row">
                            <label for="productID">Picture Product:</label>
                            <div class="input-group image-preview-container">
                                <img id="previewImage" class="image-preview" src="${pageContext.request.contextPath}/pdimg/${pdStock.pdImage}" alt="Preview Image"/>
                                <div class="input-group-append">
                                    <span class="input-group-text file-input">
                                        <input type="file" name="stockImg" id="productImage" onchange="updatePreview(event)">
                                    </span>
                                </div>
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="productName">Product Name:</label>
                            <input readonly style="width: 50%"type="text" class="form-control" id="productName" name="productName"
                                   value="${pdStock.proName}" >
                        </div>

                        <div class="form-group row">
                            <label for="color">Color:</label>
                            <input style="width: 50%"type="text" class="form-control" id="color" name="color"
                                   value="${pdStock.pdColor}">
                        </div>

                        <div class="form-group row">
                            <label for="available">Available:</label>
                            <input style="width: 50%"type="number" class="form-control" id="available" name="available" value="${pdStock.pdAvailable}">
                        </div>

                        <div class="form-group row">
                            <label for="status">Status:</label>
                            <select class="form-control" id="status" name="status" style="width: 30%">
                                <option value="1" ${pdStock.pdStatus==1 ? 'selected' : '' }>View</option>
                                <option value="0" ${pdStock.pdStatus==0 ? 'selected' : '' }>Hide</option>
                            </select>
                        </div>

                        <a class="btn btn-primary" href="./manage-productDetailStock?proId=${pdStock.proID}">Cancel</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>

            </div>
        </div>
    </body>


    <!-- =========== Scripts =========  -->
    <script src="js/admin_manager.js"></script>
    <!-- ====== ionicons ======= -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    <script>
                                            function updatePreview(event) {
                                                var input = event.target;
                                                var reader = new FileReader();

                                                reader.onload = function () {
                                                    var imgElement = document.getElementById('previewImage');
                                                    imgElement.src = reader.result;
                                                }

                                                reader.readAsDataURL(input.files[0]);
                                            }

    </script>

</html>